apps/stock_market_simulator_app/urls.py
from django.conf.urls import url
from . import views

app_name = "stock_market_sim_app"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^symbol_lookup$', views.posted_historic_stock_data, name='post_symbol'),
]

stock_market_simulator/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.stock_market_simulator_app.urls")),
]

apps/stock_market_simulator_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/stock_market_simulator_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.utils.safestring import SafeString
from django.http import JsonResponse
import ystockquote

from pprint import pprint
from datetime import datetime

# Create your views here.

def index(request):
    return render(request, 'stock_market_sim_templates/index.html')

def posted_historic_stock_data(request):

    start = request.POST['start'].split("/")
    end = request.POST['end'].split("/")
    symbol = request.POST['symbol']

    date_start = datetime(int(start[2]), int(start[0]), int(start[1])).strftime('%Y-%m-%d')


    date_end = datetime(int(end[2]), int(end[0]), int(end[1])).strftime('%Y-%m-%d')
    historic_stock_data  = JsonResponse(ystockquote.get_historical_prices(symbol, date_start, date_end))

    print ystockquote.get_200_sma('googl')


    return historic_stock_data
    # context = { "historic_stock_data": SafeString(historic_stock_data)}
    # return render(request, 'stock_market_sim_templates/hist_results.html', context)

apps/stock_market_simulator_app/templates/stock_market_sim_templates/hist_results.html
<!-- <script type="text/javascript">
  console.log({{historic_stock_data}})
  // $("#test").html(JSON.stringify({{historic_stock_data}}, null, 2))
  $("#test").append({{historic_stock_data}})
</script>
<pre id="test">

</pre>


var trace1 = {
  x: [1, 2, 3],
  y: [40, 50, 60],
  name: 'yaxis data',
  type: 'scatter'
};

var trace2 = {
  x: [2, 3, 4],
  y: [4, 5, 6],
  name: 'yaxis2 data',
  yaxis: 'y2',
  type: 'scatter'
};

var data = [trace1, trace2];

var layout = {
  title: 'Double Y Axis Example',
  yaxis: {title: 'yaxis title'},
  yaxis2: {
    title: 'yaxis2 title',
    titlefont: {color: 'rgb(148, 103, 189)'},
    tickfont: {color: 'rgb(148, 103, 189)'},
    overlaying: 'y',
    side: 'right'
  }
};

Plotly.newPlot('myDiv', data, layout); -->

apps/stock_market_simulator_app/templates/stock_market_sim_templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Stock Market Simulator</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'stock_market_sim_static/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'stock_market_sim_static/skeleton.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){

      function calculate_10_day_sma(dates, closing_price){

        var sma_dates = dates.slice(10)
        var simple_moving_average = []
        var count_range_start = 9
        var count_range_end = 0
        var counter = 0
        while(count_range_end != closing_price.length){
          var sum = 0
          for(var x = count_range_start; x >= count_range_end; x--){
            counter++
            if(closing_price[x] === undefined){
              var data = [sma_dates, simple_moving_average]
              return data;
            }
            sum += closing_price[x]
          }
          simple_moving_average.push(sum / 10);

          if(counter === 9){
            counter = 0
          }
          count_range_start++
          count_range_end++
        }
        var data = [sma_dates, simple_moving_average]
        return data


      }

      function sortDates(data){
        var dates = []
        for(val in data){
          dates.push(val)
        }
        return dates.sort()
      }

      function stockData(dates, data){
        var stockDataObj = {
          "close": [],
          "volume": [],
          "open": [],
          "high": [],
          "low": []
        }

        for(var x = 0; x < dates.length; x++){
          stockDataObj['high'].push(parseInt(data[dates[x]]["High"]))
          stockDataObj['low'].push(parseInt(data[dates[x]]["Low"]))
          stockDataObj['close'].push(parseInt(data[dates[x]]["Close"]))
          stockDataObj['volume'].push(parseInt(data[dates[x]]["Volume"]))
          stockDataObj['open'].push(parseInt(data[dates[x]]["Open"]))

          $('#test').append("<p>" + dates[x] + " : " + JSON.stringify(data[dates[x]], null, 2)+"</p>")
        }

        return stockDataObj;
      }

      $(".datepicker" ).datepicker();

      $('form').submit(function(e){
        e.preventDefault();

        $.ajax({
          url: "/symbol_lookup",
          method: 'Post',
          data: $(this).serialize(),
          success: function(data){

            var dates = sortDates(data)
            var stockDataObj = stockData(dates, data)
            var ten_day_sma = calculate_10_day_sma(dates, stockDataObj['close'])

            // BEGIN GRAPH CODE

            var trace1 = {
              x: stockDataObj['dates'],
              y: stockDataObj['volume'],
              name: 'Daily Volume Traded',
              type: 'scatter'
            };

            var data = [trace1];

            var layout = {
              title: 'Daily Volume Traded',
              yaxis: {title: 'Daily Volume Traded'},
            };

            Plotly.newPlot('myDiv', data, layout);

            var trace1 = {
              x: ten_day_sma[0],
              y: ten_day_sma[1],
              name: '10 day Simple Moving Average',
              type: 'scatter'
            };

            var data = [trace1];

            var layout = {
              title: 'Simple Moving Average',
              yaxis: {title: 'Simple Moving Average'},
            };

            Plotly.newPlot('myDiv2', data, layout);

            var trace1 = {

              x: dates,

              close: stockDataObj['close'],

              decreasing: {line: {color: '#7F7F7F'}},

              high: stockDataObj['high'],

              increasing: {line: {color: '#17BECF'}},

              line: {color: 'rgba(31,119,180,1)'},

              low: stockDataObj['low'],

              open: stockDataObj['open'],

              type: 'ohlc',
              xaxis: 'x',
              yaxis: 'y'
            };

            var data = [trace1];

            var layout = {
              dragmode: 'zoom',
              margin: {
                r: 10,
                t: 25,
                b: 40,
                l: 60
              },
              showlegend: false,
              xaxis: {
                autorange: true,
                rangeslider: {range: [dates[0], dates[dates.length-1]]},
                title: 'Date',
                type: 'date'
              },
              yaxis: {
                autorange: true,
                type: 'linear'
              },


            };

            Plotly.plot('plotly-div', data, layout);



          },
          dataType: 'json'
        })
      })
    })

  </script>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <h3>Get Historic Stock Data</h1>
        <form action="{% url 'stock_market_sim_app:post_symbol' %}", method="POST">
          {% csrf_token %}
          <p>Stock Symbol: <input type="text" name="symbol" value="googl"></p>
          <p>Start Date: <input type="text" class="datepicker" value="03/15/2017" name="start"></p>
          <p>EndDate: <input type="text" class="datepicker" name="end" value="03/31/2017"></p>
          <p><input type="submit" value="Go!"></p>
        </form>
        <p id="data">
          <div id="plotly-div" style="width: 100%; height: 600px;">

          </div>

          <div id="myDiv" style="width: 100%; height: 600px;">

          </div>

          <div id="myDiv2" style="width: 100%; height: 600px;">

          </div>


          <pre id="test">

          </pre>
        </p>
      </div>
    </div>
  </div>
</body>
</html>